##
#    SPDX-License-Identifier: BSD-2-Clause-Patent
##

#
#  PEI Phase modules
#
INF  CsdnPcPkg/MyHelloWorldPEIMHob/MyHelloWorldPEIMHob.inf
INF  CsdnPcPkg/MyHelloWorldPEIMDriver/MyHelloWorldPEIMDriver.inf
INF  CsdnPcPkg/MyHelloWorldInstallPPI/MyHelloWorldInstallPPI.inf
INF  CsdnPcPkg/MyHelloWorldLocatePPI/MyHelloWorldLocatePPI.inf
INF  CsdnPcPkg/MpServicePei/MpServicePei.inf
INF  CsdnPcPkg/PpiNotifty/PpiNotifty.inf
