##
#    SPDX-License-Identifier: BSD-2-Clause-Patent
##
#
# DXE Phase modules
#
INF  CsdnPcPkg/MyHelloWorldDXEHob/MyHelloWorldDXEHob.inf
INF  CsdnPcPkg/MyHelloWorldDXEProtocol/MyHelloWorldDXEProtocol.inf
INF  CsdnPcPkg/MyHelloWorldDXEDriver/MyHelloWorldDXEDriver.inf
INF  CsdnPcPkg/MyHelloworldInstallAcpiDxe/MyHelloworldInstallAcpiDxe.inf
INF  CsdnPcPkg/PlatformSmbiosTable/PlatformSmbiosTable.inf
INF  CsdnPcPkg/PciIoProtocolDump/PciIoProtocolDump.inf
INF  CsdnPcPkg/CreateUefiPhaseEvent/CreateUefiPhaseEvent.inf